packageExtensions:
  '@yarnpkg/cli@*':
    dependencies:
      '@yarnpkg/cli': '*'
  '@yarnpkg/core@*':
    dependencies:
      '@types/lodash': '*'
  '@yarnpkg/plugin-patch@*':
    dependencies:
      '@yarnpkg/cli': '*'
      '@yarnpkg/core': '*'
  '@yarnpkg/plugin-npm@*':
    dependencies:
      '@yarnpkg/core': '*'
      '@yarnpkg/plugin-pack': '*'
  '@yarnpkg/plugin-pack@*':
    dependencies:
      '@yarnpkg/cli': '*'
  webpack@*:
    dependencies:
      terser-webpack-plugin: '*'
